### ISSUE TITLE
Connect to multiple JIRA instances directly to report time

### ISSUE THREAD

**Issue by kosperera** [99xt/jira-journal#15]
Right now we are authenticating via Seranet which is a 99XT specific service. In the future, we need like to skip Seranet and go ahead directly with JIRA REST API for reporting time.

**Work items**

- [ ] Sign in card to authenticate via multiple JIRA instances
- [ ] Time report to authenticated JIRA instances
- [ ] Showing all assigned and recently used tasks from connected JIRA instances
- [ ] Get rid of Seranet
- [ ] Sign out from connected JIRA instances
